name: GeoValuator
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10.13
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - yaml
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8 
  - pillow
  - geopandas
  - shapely
  - rtree
  - scipy
  - contextily
  - pyyaml
  - pip:
    - python-dotenv
    - osmnx
    - utm
    - folium
    - requests
    - timm
    - albumentations
    - opencv-python
    - seaborn
    - -e .