name: GeoValuator
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10.13
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - ruff
  - yaml
  - pytorch
  - torchvision
  - torchaudio
  - pip:
    - python-dotenv
    - osmnx
    - utm
    - folium
    - requests
    - shapely
    - rtree
    - contextily
    - timm
    - -e .
