[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GeoValuator"
version = "0.0.1"
description = "ML Handson Final Project"
authors = [
  { name = "Lucas\u0026Leonardo" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "==3.10.13"


[tool.ruff]
line-length = 99
src = ["GeoValuator"]
include = ["pyproject.toml", "GeoValuator/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["GeoValuator"]
force-sort-within-sections = true

